### ISSUE TITLE
Glitchy Resizing when Hovering over Stylist HeaderBar Card.

### ISSUE THREAD

**Issue by TheParodicts** [uprm-inso-4101-2020-2021-S1/semester-project-the-first-team#8]
After a merge of the frontend, when hovering over the stylist header bar card, specifically the edges of the card, this causes the stylist view body size to suddenly change back and forth. This resizes the container so quickly as to seem like the site is vibrating, showing and hiding a scroll bar. 

This could be an issue with the CSS when merging. Needs to be looked into.

**Comment by milton-pagan** [comment]
I think this issue was resolved, so I'm closing it.
